### ISSUE TITLE
Allow output in standard formats

### ISSUE THREAD

**Issue by ChrisA89** [sksamuel/sbt-scapegoat#16]
The xml output generated at the moment seems to be custom to this project.
It would be useful if it could be in a format that is more Jenkins friendly (checkstyle, findbugs, PMD, etc.)

The checkstyle XmlLogger code is [here](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java). It produces something like:
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="5.0">
  <file name="C:\Workspace\default_ant\src\org\sprunck\foo\Foo.java">
    <error line="10" message="Line has trailing spaces." severity="error" source="com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineCheck"></error>        
    <error line="20" message="Line has trailing spaces." severity="error" source="com.puppycrawl.tools.checkstyle.checks.regexp.RegexpSinglelineCheck"></error>            
    <error column="26" line="30" message="'Went' entspricht nicht dem Muster '^[a-z][a-zA-Z0-9]*$'." severity="error" source="com.puppycrawl.tools.checkstyle.checks.naming.MethodNameCheck"></error>
  </file>
</checkstyle>
```

**Comment by Axblade** [comment]
This should be done in [scalac-scapegoat-plugin](https://github.com/sksamuel/scalac-scapegoat-plugin), isn't it? 

I'm looking for a way to display sbt-scapegoat output in jenkins with nice looking graphs and other shiny things. If my assumption is right, I'd like to take care about this issue.

**Comment by Axblade** [comment]
Or may be, it will be better to write plugin for jenkins? But this way is not so easy and fast I think.
@ChrisA89, @sksamuel, what do you think?

**Comment by ChrisA89** [comment]
You're right it should be in [scalac-scapegoat-plugin](https://github.com/sksamuel/scalac-scapegoat-plugin). You could build a Jenkins plugin to support scapegoat, but in my opinion that's working around the problem rather than fixing it.

**Comment by Axblade** [comment]
I pushed a [merge request](https://github.com/sksamuel/scalac-scapegoat-plugin/pull/99) to scalac-scapegoat-plugin.
Please, review it.

**Comment by sksamuel** [comment]
Thanks for pr.

**Comment by ChrisA89** [comment]
Awesome thanks!

**Comment by Green-Angry-Bird** [comment]
+1

**Comment by sksamuel** [comment]
The sbt plugin needs to be updated now to use this.

**Comment by gregsymons** [comment]
Like #19, if you don't already have this in progress, I'd be willing to work on it, since I'd like to see both :)

**Comment by sksamuel** [comment]
Definitely crack on :)

**Comment by gregsymons** [comment]
After taking a closer look at sksamuel/scalac-scapegoat-plugin#99, it looks like all that's really needed to resolve this issue is a new release of the compiler plugin and a bump to the default version that gets pulled in, since the scalastyle format report is turned on by default.

**Comment by gregsymons** [comment]
That said, I'm working on patches for both sksamual/scalac-scapegoat-plugin and the sbt plugin to make it possible to pick which reports you want. Expect pull requests soon.
