### ISSUE TITLE
Create sbt task for scapegoat

### ISSUE THREAD

**Issue by chabala** [sksamuel/sbt-scapegoat#19]
Currently configuring an sbt project to use scapegoat has the effect that scapegoat will run during the compile phase, as configured, every time.

Please create an sbt task that will allow scapegoat to run on demand, and decouple from running during the default compilation phase, as is the case with [scalastyle](http://www.scalastyle.org/sbt.html#usage). This will allow users to optionally run scapegoat periodically, and otherwise run the build without penalizing compile times.

**Comment by KyleU** [comment]
This is particularly important since SBT's incremental compile means Scapegoat only runs on modified files, overwriting reports, unless you clean first.

**Comment by sksamuel** [comment]
It's in the works for May :)

**Comment by gregsymons** [comment]
Any updates on this? If you haven't already got it started, I may be willing to take a swing at it.

**Comment by sksamuel** [comment]
Please do :)
