### ISSUE TITLE
Scapegoat forces a clean

### ISSUE THREAD

**Issue by sebastiaansamyn-tc** [sksamuel/sbt-scapegoat#31]
The scapegoat task has a hard dependency on clean, this empties the target folder and doesn't play nicely together with other tools like scoverage, because it not only removes its own reports but the entire target folder if you run something like `sbt scoverage scapegoat`.

https://github.com/sksamuel/sbt-scapegoat/blob/master/src/main/scala/com/sksamuel/scapegoat/sbt/ScapegoatSbtPlugin.scala#L79

What is the reasoning behind this? Wouldn't it be possible to only remove the scapegoatOutputPath?

**Comment by sksamuel** [comment]
The rationale was that if you do `scapegoat` without clean then sbt won't actually do anything because the files haven't changed. There is probably a way around this but my sbt knowledge isn't that good.

**Comment by sebastiaansamyn-tc** [comment]
Currently, I don't have the time to dig into this, but I'll try and have a look when I do...

**Comment by gregsymons** [comment]
This was something I added (#24), and I'm not 100% sure I was correct when I did.

I've been getting bit by this issue myself, since I have a plugin that aggregates several other plugins and scapegoat keeps blowing away their output :) I've been meaning to open a PR to remove the dependency on clean.

**Comment by sksamuel** [comment]
@gregsymons @sebastiaansamyn-tc might be better to just state "you must run clean first if you want fresh output from scapegoat" ?

**Comment by gregsymons** [comment]
It _kinda_ works if you just remove the clean... it reruns scapegoat only on files that have changed. I'm working on adding a "force" option that will delete just the scapegoat output dir and force analysis of all files.

**Comment by sksamuel** [comment]
That sounds ideal
