### ISSUE TITLE
publish to central

### ISSUE THREAD

**Issue by fommil** [sksamuel/sbt-scapegoat#33]
same story as scoverage

```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.10;1.0.0: not found
```

**Comment by orElse** [comment]
from the documentation the plugin is only supported for scala 2.11 - you are trying to load it for scala 2.10

**Comment by sksamuel** [comment]
Yes this isn't supported for 2.10 Sam @fommil

**Comment by rgjamkhedkar** [comment]
I am getting similar error for Scala 2.12 - 
unresolved dependency: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.12;1.0.0: not found.

I have added following in plugins.sbt
`
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.4")
`

**Comment by ikr0m** [comment]
I've got same error
`unresolved dependency: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.12;1.0.0: not found`

**Comment by sksamuel** [comment]
1.0.7 is the scala 2.12 release.
