### ISSUE TITLE
scalacOptions doesn't work

### ISSUE THREAD

**Issue by missingfaktor** [sksamuel/sbt-scapegoat#38]
Putting `scalacOptions += "-P:scapegoat:overrideLevels:TraversableHead=Warning:OptionGet=Warning"` in `build.sbt` produces following error on `sbt compile`:

``` sbt
[error] bad option: -P:scapegoat:overrideLevels:TraversableHead=Warning:OptionGet=Warning
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

**Comment by mkistler** [comment]
I encountered the same problem but I think I found a workaround.  It seems that you can tell set to use these scalacOptions only for scapegoat, as follows:

```
scalacOptions in Scapegoat += "-P:scapegoat:overrideLevels:TraversableHead=Warning:OptionGet=Warning"
```
