### ISSUE TITLE
Publish for Scala v2.12.0

### ISSUE THREAD

**Issue by marconilanna** [sksamuel/sbt-scapegoat#42]
The [Scala 2.12.0 release train](https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md) is here. Please publish for 2.12.0 and [submit a pull request](https://github.com/scala/make-release-notes/edit/2.12.x/projects-2.12.md) to let the world know what libraries are available.

**Comment by Krever** [comment]
Hi guys, is there any chance to moving it through?

**Comment by sksamuel** [comment]
the sbt plugin doesn't need a release since sbt is always 2.10. All you need to do is set the version of scapegoat you want (for 2.12) as per the readme.

**Comment by sksamuel** [comment]
@marconilanna I added a PR to that page.

**Comment by Krever** [comment]
For me https://github.com/sksamuel/sbt-scapegoat/issues/45 was the case.
