### ISSUE TITLE
support for sbt-scapegoat_2.11

### ISSUE THREAD

**Issue by saj1th** [sksamuel/sbt-scapegoat#59]
Looks like there is no support for scala 2.11  for sbt-scapegoat
https://repo1.maven.org/maven2/com/sksamuel/scapegoat/

Spark 2.2.0 uses Scala 2.11 and it'll be useful to have 2.11 support

thanks
sajith

**Comment by pomadchin** [comment]
This issue was addressed here: https://github.com/sksamuel/sbt-scapegoat/pull/58

**Comment by pomadchin** [comment]
Hey, 1.0.8 version is released :tada:
