### ISSUE TITLE
how to fail scapegoat task if an error is found?

### ISSUE THREAD

**Issue by drorasaf** [sksamuel/sbt-scapegoat#60]

**Comment by drorasaf** [comment]
just use scapegoatMaxErrors and set it to 1.

**Comment by antoon-r** [comment]
How do I use scapegoatMaxErrors option?

I am using 1.0.5 plugin version. I set it to 1000 in my `build.sbt`:

> scapegoatMaxErrors in ThisBuild := 1000

But it anyway fails the build.
