### ISSUE TITLE
Plugin dependency isn't resolved

### ISSUE THREAD

**Issue by daron666** [sksamuel/sbt-scapegoat#63]
Can't add plugin even to a dummy project.

Project as a gist is here: https://gist.github.com/daron666/a34cea78c9a20f8f6243e6c635f0362b

![screen shot 2018-02-02 at 09 25 55](https://user-images.githubusercontent.com/1447374/35717857-2310d906-07fb-11e8-8138-a62454adb8ad.png)

I'm using Idea as a IDE, but even from command line I wasn't able to run `scapegoat` task and got this error
```
sbt:scapegoat-not-working> scapegoat
[info] [scapegoat] Removing scapegoat class directory: /Users/daron/IdeaProjects/scapegoat-not-working/target/scala-2.12/scapegoat-classes
[error] java.lang.Exception: Fatal: scalac-scapegoat-plugin not in libraryDependencies (Vector(/Users/daron/.sbt/boot/scala-2.12.4/lib/scala-library.jar))
[error] 	at com.sksamuel.scapegoat.sbt.ScapegoatSbtPlugin$.$anonfun$projectSettings$4(ScapegoatSbtPlugin.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Scapegoat / scalacOptions) java.lang.Exception: Fatal: scalac-scapegoat-plugin not in libraryDependencies (Vector(/Users/daron/.sbt/boot/scala-2.12.4/lib/scala-library.jar))
[error] Total time: 0 s, completed Feb 2, 2018 9:30:14 AM
```

What am I doing wrong?

**Comment by pomadchin** [comment]
Indeed, there is a bug introduced by a `provided` scope in my PR https://github.com/sksamuel/sbt-scapegoat/pull/58 and after investigating this issue it turned out that https://github.com/sksamuel/sbt-scapegoat/pull/62 even make the issue harder. Can you take a look into #64 and double check that it resolves this issue?

**Comment by pomadchin** [comment]
@ireactsam yep, i checked it locally. release date is only up to @sksamuel

**Comment by mwz** [comment]
+1 for a new release :)

**Comment by sksamuel** [comment]
1.0.9 is released! @mwz @pomadchin @ireactsam

**Comment by ches** [comment]
Even after the changes to `Provided` scope it's still possible to get into some situations where you'll have

> scalac-scapegoat-plugin not in libraryDependencies

I'm playing with some ways to patch this to try to make it still more robust, but something to check if you're having this problem: don't replace `libraryDependencies` with `:=` or you'll override the inclusion from this plugin.

```scala
// BAD
lazy val yourproject = project.settings(libraryDependencies := Seq(stuff))

// GOOD
lazy val yourproject = project.settings(libraryDependencies ++= Seq(stuff))
```

**Comment by mwz** [comment]
Might be worth adding a quick note to the readme and also maybe expanding on [this](https://github.com/sksamuel/sbt-scapegoat/blob/master/src/main/scala/com/sksamuel/scapegoat/sbt/ScapegoatSbtPlugin.scala#L69) error message suggesting to the user to double check that they didn't accidentally overwrite library dependencies.
