### ISSUE TITLE
Update scalac-scapegoat-plugin version or find a flexible way to determine it.

### ISSUE THREAD

**Issue by marnux** [sksamuel/sbt-scapegoat#69]
As there are more people using scala 2.12 exclusively, it might be a good idea to update the version as there is no scalac-scapegoat-plugin 1.0.0 available for scala 2.12

**Comment by BalmungSan** [comment]
+1

**Comment by marnux** [comment]
I tried that but as soon as i start sbt, it still wants to pull in the 1.0.0 for scala 2.12. If that would have worked, i wouldn't have opened an issue.

**Comment by BalmungSan** [comment]
Really ?

I had just deleted my _~/.ivy2/cache/_ folder and started a new fresh sbt session in a project that uses scapegoat. and it only downloaded the following two artifacts related to scapegoat.

> com.sksamuel.scapegoat#sbt-scapegoat;1.0.9!sbt-scapegoat.jar 
> com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.12;1.3.4!scalac-scapegoat-plugin_2.12.jar

**Comment by marnux** [comment]
Will give it another try and see what happens and clean the whole cache to be certain.

**Comment by BalmungSan** [comment]
Ok, 

If you still had the problem after that, you could create a dummy repo that replicates the problem, I will be happy to clone that repo and check what is making it fail.

Maybe one of your plugins or dependencies is the one that is trying to get the scapegoat plugin 1.0.0 ?

**Comment by marnux** [comment]
I haven't figured it out yet, but when creating a new project with only scapegoat plugin, the dependency resolution works as described with the `scapegoatVersion in ThisBuild`.
Will have to go with your comment, that it is something else in the project that triggers that depenency.

**Comment by mr-git** [comment]
got the same issue on multi-module project. 
added:
* `addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.9")`
* `scapegoatVersion := "1.3.8"` shows red/error in IDEA

trying to reload SBT session fails with missing `com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.12:1.0.0:`

**Comment by mr-git** [comment]
ok, got this working...
in root aggregator module, I had to add explicitly
```
  .settings (inThisBuild(Seq(scapegoatVersion := "1.3.8")))
```
as I have 
```
object BuildSettings {
  // ThisBuild settings take lower precedence, but can be shared across the multi projects.
  lazy val thisBuildSettings: Seq[Setting[_]] = inThisBuild(Seq(
//...
    scapegoatVersion := "1.3.8"
))
}
``` which doesn't get loaded (as it is lazy) soon enough and SBT sees hardcoded `1.0.0` version instead
