### ISSUE TITLE
sbt-scapegoat doesn't work with sbt 1.2.x

### ISSUE THREAD

**Issue by tartakynov** [sksamuel/sbt-scapegoat#87]
According to `build.sbt` currently sbt-scapegoat is cross compiled for 0.13.x, 1.1x but not for 1.2.x.

sbt 1.2.x has been around for a year, it's very stable now and lots of organizations and projects are using it

**Comment by sksamuel** [comment]
PR welcome.

**Comment by tartakynov** [comment]
Actually, never mind, I was wrong. It does work with sbt 1.2.x with scala 2.12, just need to update `scapegoatVersion` to 1.3.8
